### ISSUE TITLE
error when running cli.py in pyunity-gui

### ISSUE THREAD

**Issue by halfrender** [pyunity/pyunity-gui#2] opened 2021-07-05 02:58 UTC
so.. i was just trying out pyunity-gui..
and got this error:
```
Loaded config
Trying GLFW as a window provider
Using window provider GLFW
Loaded PyUnity version 0.7.0
Traceback (most recent call last):
  File "C:\Users\Lenovo\Downloads\pyunity-gui\editor\render.py", line 26, in initializeGL
    self.original.Start()
  File "scene.py", line 328, in pyunity.scenes.scene.Scene.Start
  File "render.py", line 233, in pyunity.render.Camera.Resize
  File "E:\Programming\Python38-32\lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src\errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glViewport,
        cArguments = (0, 0, 800, 500)
)
```
PS. i tried reinstalling pyopengl and pyunity but still this happens

**Comment by rayzchen** [comment] 2021-07-05 13:11
It requires you to run `install.py` first.

**Comment by ayuvius** [comment] 2021-07-05 14:02
after running install.py..
this again happened..

**Comment by adityadasch** [comment] 2021-07-05 14:29
Wait I will inform Ray about this

**Comment by rayzchen** [comment] 2021-07-05 15:11
What is the output of running `install.py`? If you haven't, try pulling the latest changes.

**Comment by ayuvius** [comment] 2021-07-06 02:55
install.py:
```
Collecting pyunity@ https://ci.appveyor.com/api/buildjobs/t2ike2y4gno1qmov/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl
  Downloading https://ci.appveyor.com/api/buildjobs/t2ike2y4gno1qmov/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl (3.9 MB)
     |████████████████████████████████| 3.9 MB 124 kB/s
Requirement already satisfied: pysdl2-dll in e:\programming\python38-32\lib\site-packages (from pyunity@ https://ci.appveyor.com/api/buildjobs/t2ike2y4gno1qmov/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl) (2.0.14.post2)
Requirement already satisfied: pyopengl in e:\programming\python38-32\lib\site-packages (from pyunity@ https://ci.appveyor.com/api/buildjobs/t2ike2y4gno1qmov/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl) (3.1.5)
Requirement already satisfied: pyglm in e:\programming\python38-32\lib\site-packages (from pyunity@ https://ci.appveyor.com/api/buildjobs/t2ike2y4gno1qmov/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl) (2.2.0)
Requirement already satisfied: pysdl2 in e:\programming\python38-32\lib\site-packages (from pyunity@ https://ci.appveyor.com/api/buildjobs/t2ike2y4gno1qmov/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl) (0.9.7)
Requirement already satisfied: glfw in e:\programming\python38-32\lib\site-packages (from pyunity@ https://ci.appveyor.com/api/buildjobs/t2ike2y4gno1qmov/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl) (2.1.0)
Requirement already satisfied: pillow in e:\programming\python38-32\lib\site-packages (from pyunity@ https://ci.appveyor.com/api/buildjobs/t2ike2y4gno1qmov/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl) (8.2.0)
```

**Comment by ayuvius** [comment] 2021-07-06 02:57
and cli.py:
```
Loaded config
Trying GLFW as a window provider
Using window provider GLFW
Loaded PyUnity version 0.7.0
None
None
<Transform position=Vector3(0.0, 0.0, 0.0) rotation=Quaternion(1.0, 0.0, 0.0, 0.0) scale=V
ector3(1.0, 1.0, 1.0) path="/Main Camera">
Traceback (most recent call last):
  File "C:\Users\Lenovo\Downloads\pyunity-gui\editor\render.py", line 26, in initializeGL
    self.original.Start()
  File "scene.py", line 328, in pyunity.scenes.scene.Scene.Start
  File "render.py", line 233, in pyunity.render.Camera.Resize
  File "E:\Programming\Python38-32\lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src\errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glViewport,
        cArguments = (0, 0, 800, 500)
)
```

**Comment by rayzchen** [comment] 2021-07-07 20:14
I cannot reproduce, could you give me more information? Try running `install.py` again with the new changes, before it was a bit broken.

**Comment by rayzchen** [comment] 2021-07-07 20:33
Another thing to check is at the botton of `editor/render.py`, does it contain the line `self.makeCurrent()`?
![image](https://user-images.githubusercontent.com/54078384/124824924-e10a2d00-df6a-11eb-84ae-a35d70739ae0.png)
Your error indicates that the QOpenGLWidget seems to not have a context, or it is invalid when `scene.Start()` is run.

**Comment by ayuvius** [comment] 2021-07-08 03:18
install.py:
```
WARNING: Skipping pyunity as it is not installed.
Collecting pyunity@ https://ci.appveyor.com/api/buildjobs/y1uj355xc9opqvya/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl
  Downloading https://ci.appveyor.com/api/buildjobs/y1uj355xc9opqvya/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl (3.9 MB)
     |████████████████████████████████| 3.9 MB 52 kB/s
Requirement already satisfied: pysdl2 in e:\programming\python38-32\lib\site-packages (from pyunity@ https://ci.appveyor.com/api/buildjobs/y1uj355xc9opqvya/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl) (0.9.7)
Requirement already satisfied: pyopengl in e:\programming\python38-32\lib\site-packages (from pyunity@ https://ci.appveyor.com/api/buildjobs/y1uj355xc9opqvya/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl) (3.1.5)
Requirement already satisfied: pyglm in e:\programming\python38-32\lib\site-packages (from pyunity@ https://ci.appveyor.com/api/buildjobs/y1uj355xc9opqvya/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl) (2.2.0)
Requirement already satisfied: pillow in e:\programming\python38-32\lib\site-packages (from pyunity@ https://ci.appveyor.com/api/buildjobs/y1uj355xc9opqvya/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl) (8.2.0)
Requirement already satisfied: glfw in e:\programming\python38-32\lib\site-packages (from pyunity@ https://ci.appveyor.com/api/buildjobs/y1uj355xc9opqvya/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl) (2.1.0)
Requirement already satisfied: pysdl2-dll in e:\programming\python38-32\lib\site-packages (from pyunity@ https://ci.appveyor.com/api/buildjobs/y1uj355xc9opqvya/artifacts/dist/pyunity-0.7.0-cp38-cp38-win32.whl) (2.0.14.post2)
Installing collected packages: pyunity
Successfully installed pyunity-0.7.0
```
cli.py:
```
Loaded config
Trying GLFW as a window provider
Using window provider GLFW
Loaded PyUnity version 0.7.0
None
None
None
<Transform position=Vector3(0.0, 0.0, 0.0) rotation=Quaternion(1.0, 0.0, 0.0, 0.0) scale=Vector3(1.0, 1.0, 1.0) path="/Root">
<Transform position=Vector3(0.0, 0.0, 0.0) rotation=Quaternion(1.0, 0.0, 0.0, 0.0) scale=Vector3(1.0, 1.0, 1.0) path="/Root">
<Transform position=Vector3(0.0, 0.0, 0.0) rotation=Quaternion(1.0, 0.0, 0.0, 0.0) scale=Vector3(1.0, 1.0, 1.0) path="/Root">
<Transform position=Vector3(0.0, 0.0, 0.0) rotation=Quaternion(1.0, 0.0, 0.0, 0.0) scale=Vector3(1.0, 1.0, 1.0) path="/Root">
<Transform position=Vector3(0.0, 0.0, 0.0) rotation=Quaternion(1.0, 0.0, 0.0, 0.0) scale=Vector3(1.0, 1.0, 1.0) path="/Root">
<Transform position=Vector3(0.0, 0.0, 0.0) rotation=Quaternion(1.0, 0.0, 0.0, 0.0) scale=Vector3(1.0, 1.0, 1.0) path="/Root">
Traceback (most recent call last):
  File "E:\Programming\cmder\pyunity-gui\editor\render.py", line 26, in initializeGL
    self.original.Start()
  File "scene.py", line 325, in pyunity.scenes.scene.Scene.Start
  File "render.py", line 235, in pyunity.render.Camera.Resize
  File "E:\Programming\Python38-32\lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src\errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glViewport,
        cArguments = (0, 0, 800, 500)
)
```



> Another thing to check is at the botton of `editor/render.py`, does it contain the line `self.makeCurrent()`?
> ![image](https://user-images.githubusercontent.com/54078384/124824924-e10a2d00-df6a-11eb-84ae-a35d70739ae0.png)
> Your error indicates that the QOpenGLWidget seems to not have a context, or it is invalid when `scene.Start()` is run.

yes the line is there..

. please ask if you want more information.. i am always there to reply

**Comment by ayuvius** [comment] 2021-07-09 05:30
why isn't my issue fixed yet?

**Comment by rayzchen** [comment] 2021-07-09 05:48
I can't seem to reproduce the issue.

**Comment by rayzchen** [comment] 2021-07-12 07:52
Closing this issue as I haven't seen anyone else have this error.

**Closed as completed by rayzchen** 2021-07-12 07:52 UTC
Labels: bug, help wanted, invalid
